# Generated by Django 4.1.6 on 2023-02-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_categoria_alter_video_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
