# Generated by Django 4.1.6 on 2023-02-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('videos', '0004_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoriaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='categorias.categoria'),
        ),
    ]
