# Generated by Django 4.1.6 on 2023-02-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('cor', models.CharField(choices=[('VM', 'Vermelho'), ('VD', 'Verde'), ('AZ', 'Azul'), ('AM', 'Amarelo'), ('L', 'Laranja'), ('R', 'Rosa')], default='VM', max_length=2)),
            ],
        ),
    ]
